import img_1 from "../../assets/pictures/dolphins/1.png";
import img_2 from "../../assets/pictures/dolphins/2.png";
import img_3 from "../../assets/pictures/dolphins/3.png";
import img_4 from "../../assets/pictures/dolphins/4.png";
import img_5 from "../../assets/pictures/dolphins/5.png";
import img_6 from "../../assets/pictures/dolphins/6.png";
import img_7 from "../../assets/pictures/dolphins/1R.png";

export const scheduler = [
  {
    day: "Понеделник",
    column_1: { icon: "", teacher: "" },
    column_2: { icon: "", teacher: "" },
    column_3: { icon: "", teacher: "" },
    column_4: { icon: "", teacher: "" },
    column_5: { icon: "", teacher: "" },
    column_6: { icon: "", teacher: "" },
    column_7: { icon: "", teacher: "" },
    column_8: { icon: "", teacher: "" },
    column_9: { icon: "", teacher: "" },
    column_10: { icon: img_1, teacher: "Ленка" },
    column_11: { icon: img_1, teacher: "Ленка" },
  },
  {
    day: "Вторник",
    column_1: { icon: "", teacher: "" },
    column_2: { icon: img_2, teacher: "Росен" },
    column_3: { icon: img_3, teacher: "Росен" },
    column_4: { icon: img_3, teacher: "Росен" },
    column_5: { icon: img_3, teacher: "Росен" },
    column_6: { icon: img_3, teacher: "Росен" },
    column_7: { icon: img_3, teacher: "Росен" },
    column_8: { icon: img_3, teacher: "Росен" },
    column_9: { icon: img_4, teacher: "Росен" },
    column_10: { icon: img_1, teacher: "Росен" },
    column_11: { icon: img_5, teacher: "Росен" },
  },
  {
    day: "Сряда",
    column_1: { icon: "", teacher: "" },
    column_2: { icon: "", teacher: "" },
    column_3: { icon: img_1, teacher: "Ленка" },
    column_4: { icon: "", teacher: "" },
    column_5: { icon: "", teacher: "" },
    column_6: { icon: img_2, teacher: "Росен" },
    column_7: { icon: "", teacher: "" },
    column_8: { icon: img_1, teacher: "Ленка" },
    column_9: { icon: "", teacher: "" },
    column_10: { icon: "", teacher: "" },
    column_11: { icon: img_1, teacher: "Ленка" },
  },
  {
    day: "Четвъртък",
    column_1: { icon: "", teacher: "" },
    column_2: { icon: "", teacher: "" },
    column_3: { icon: img_1, teacher: "Ленка" },
    column_4: { icon: "", teacher: "" },
    column_5: { icon: "", teacher: "" },
    column_6: { icon: img_2, teacher: "Росен" },
    column_7: { icon: "", teacher: "" },
    column_8: { icon: img_1, teacher: "Ленка" },
    column_9: { icon: "", teacher: "" },
    column_10: { icon: "", teacher: "" },
    column_11: { icon: img_1, teacher: "Ленка" },
  },
  {
    day: "Петък",
    column_1: { icon: "", teacher: "" },
    column_2: { icon: img_2, teacher: "Росен" },
    column_3: { icon: img_3, teacher: "Росен" },
    column_4: { icon: img_3, teacher: "Росен" },
    column_5: { icon: img_3, teacher: "Росен" },
    column_6: { icon: img_3, teacher: "Росен" },
    column_7: { icon: img_3, teacher: "Росен" },
    column_8: { icon: img_3, teacher: "Росен" },
    column_9: { icon: img_4, teacher: "Росен" },
    column_10: { icon: img_1, teacher: "Росен" },
    column_11: { icon: img_5, teacher: "Росен" },
  },
  {
    day: "Събота",
    column_1: { icon: "", teacher: "" },
    column_2: { icon: img_2, teacher: "Росен" },
    column_3: { icon: img_3, teacher: "Росен" },
    column_4: { icon: img_3, teacher: "Росен" },
    column_5: { icon: img_3, teacher: "Росен" },
    column_6: { icon: img_3, teacher: "Росен" },
    column_7: { icon: img_3, teacher: "Росен" },
    column_8: { icon: img_3, teacher: "Росен" },
    column_9: { icon: img_4, teacher: "Росен" },
    column_10: { icon: img_1, teacher: "Росен" },
    column_11: { icon: img_5, teacher: "Росен" },
  },
];
